language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

notifications:
  email: false

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin
  - go get -u github.com/mitchellh/gox
  - go get -u -t ./...

script:
  - golangci-lint run
  - go test -v -race ./...
  - gox ./server && gox ./client
